import Head from "next/head";
import React from "react";
import { useTheme } from "../../contexts/ThemeContextProvider";
import { HospitalTemplate } from "../../templates/HospitalTemplate";

const Hospital = ({ data }) => {
  const { theme } = useTheme();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content={theme.accent} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HospitalTemplate data={data} />
    </div>
  );
};

export async function getServerSideProps(ctx) {
  const { id } = ctx.params;

  const url = `http://192.168.3.51:8000/hospitals?hfhudcode=${id}`;

  const res = await fetch(url);

  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default Hospital;
