version: "3.3"

services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "haynako"
      MYSQL_PASSWORD: "haynako"
      MYSQL_DATABASE: "covid_tracker"
    command: --secure-file-priv=/tmp/

  redis:
    image: redis
    ports:
      - "6379:6379"

  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
