import Head from "next/head";
import { useQuery } from "react-query";
import { useLocation } from "../contexts/LocationContextProvider";
import { useTheme } from "../contexts/ThemeContextProvider";
import { HomeTemplate } from "../templates/HomeTemplate";

export default function Home() {
  const { theme } = useTheme();
  const { regionRes, cityMunPSGC } = useLocation();

  const getCases = async () => {
    let url = "http://192.168.3.51:8000/cases";
    if (regionRes != "undefined" && regionRes) {
      url = `http://192.168.3.51:8000/cases?RegionRes=${regionRes}`;
    }
    if (cityMunPSGC && cityMunPSGC !== "all") {
      url = `http://192.168.3.51:8000/cases?CityMunPSGC=${cityMunPSGC}`;
    }

    const data = await fetch(url);

    return await data.json();
  };

  const { data, isFetching, error, refetch } = useQuery(
    ["cases", regionRes, cityMunPSGC],
    getCases,
    {
      staleTime: 120000,
      keepPreviousData: true,
    }
  );

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content={theme.primaryLight} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeTemplate
        refetch={refetch}
        data={data}
        error={error}
        isLoading={isFetching}
      />
    </div>
  );
}
