import Head from "next/head";
import { useQuery } from "react-query";
import { useTheme } from "../contexts/ThemeContextProvider";
import Map from "../components/Map";
import styled from "styled-components";

const Container = styled.div`
  .map-wrapper {
    width: 100%;
    height: 90vh;
  }
`;

export default function MapPage() {
  const { theme } = useTheme();

  const getCases = async () => {
    let url = "http://192.168.3.51:8000/coords";

    const data = await fetch(url);

    return await data.json();
  };

  const { data, isFetching, error, refetch } = useQuery("coords", getCases, {
    staleTime: 120000,
    keepPreviousData: true,
  });

  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <style>{"body{overflow:hidden;}"}</style>
        <meta name="description" content="Generated by create next app" />
        <meta name="theme-color" content={theme.primaryLight} />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="map-wrapper">
        <Map coords={data} isLoading={isFetching} />
      </div>
    </Container>
  );
}
